# Generated by Django 4.2.1 on 2023-05-28 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do curso')),
                ('description', models.TextField(null=True, verbose_name='Descrição do Curso')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Preço do Curso')),
                ('duracao', models.IntegerField(null=True, verbose_name='Duração do Curso (em horas)')),
                ('aulas', models.IntegerField(null=True, verbose_name='Número de aulas')),
                ('urlVideo', models.URLField(null=True, verbose_name='Link do vídeo da carta de vendas no Youtube')),
                ('h1', models.CharField(max_length=100, null=True, verbose_name='Header Principal (h1) da Página')),
                ('h2', models.TextField(null=True, verbose_name='Header Secundário (h2) da Página')),
                ('cta', models.CharField(max_length=100, null=True, verbose_name='Chamada para ação do botão (CTA)')),
                ('autoridade', models.TextField(null=True, verbose_name='Argumento de autoridade')),
                ('beneficios', models.TextField(null=True, verbose_name='Benefícios de absorver o conteúdo do curso')),
                ('argumentos', models.TextField(null=True, verbose_name='Argumentos e dados que comprovam os benefícios do curso')),
                ('urlVenda', models.URLField(blank=True, null=True, verbose_name='Link da página de checkout da Hotmart referente ao curso (pay.hotmart.com)')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=150, verbose_name='Pegunta Faq')),
                ('resposta', models.TextField(null=True, verbose_name='Resposta Faq')),
            ],
            options={
                'verbose_name': 'Faq Geral',
                'verbose_name_plural': 'Faq Geral',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='alunos')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome do aluno')),
                ('profissao', models.CharField(max_length=100, null=True, verbose_name='Profissão')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
