# Generated by Django 4.2.1 on 2023-08-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_curso_price_curso_pricelive_curso_pricepres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='diferencial',
            field=models.TextField(null=True, verbose_name='Diferencial, o que vai aprender na prática'),
        ),
    ]
